# Generated by Django 4.1.7 on 2023-03-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dni', models.PositiveBigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('type_of_service', models.CharField(max_length=200)),
                ('initial_date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('discount_initial_date', models.DateTimeField(blank=True, null=True)),
                ('discount_end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
